#
# Configuration for environment
#
version: 1.0
app:
  # build id to deploy. if 'version' is commented out, the application is not deployed
  version: "bcaf0bea-87b1-4164-b0ab-e1784cf07bbb"
  
  # number of instances
  instances:
    # min number of instances. can be 0 for scale to 0. default to 1.
    min: 1
    
    # max number of instances. defaults to 1 if min == 0, otherwise defaults to min
    max: 1
    
  resources:
    # max cpu. memory limit is based on cpu value: 1:4 memory ratio, e.g. 1 cpu == 4 gb
    cpu: 1

  # List of environment variables that are set for the application
  env:
    - name: SOME_ENV_VAR_NAME
      value: "some_env_var_value"

  # List of variables that can be referenced in the server.xml
  variables:
    - name: some_liberty_variable_name
      value: "some_liberty_variable_value"

  services:
  - crn: crn:v1:bluemix:public:dashdb-for-transactions:us-south:a/658cf0cdf60b98e5d2b7f0ab30ed6862:78a8d176-3fa2-466f-a19b-d8dbb26b1654::
